apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubemongoapp
  labels:
    app: kubemongoapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kubemongoapp
  template:
    metadata:
      labels:
        app: kubemongoapp
    spec:
      containers:
        - name: kubemongoapp
          image: vnarayanan/kube-mongodb:1.0.0
          ports:
            - containerPort: 5000
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: kubemongoapp-svc
spec:
  selector:
    app: kubemongoapp
  ports:
    - port: 8080
      targetPort: 5000
  type: LoadBalancer