---
version: "3.7"
services:
  py-mongo:
    # build the image from Dockerfile
    build:
      context: .
    # bind mount volume for MongoDB documents
    volumes:
      - ./mongo-data:/data/db
      - ./mongo-app:/var/www/html
    ports:
      - "27017:27017"
    # configure the Docker entrypoint for MongoDB
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongodb-user
      - MONGO_INITDB_ROOT_PASSWORD=mongodb-pwd
